<div class="space-y-6" x-data="{ modal: null }" x-on:close-resource-modal.window="modal = null" x-on:close-dashboard-modal.window="modal = null">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div class="flex items-start gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><x-ui.icon name="tags" class="h-5 w-5" /></span><div><p class="text-sm font-medium text-indigo-600 dark:text-indigo-400">Gestão</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-zinc-950 dark:text-white">Categorias</h1><p class="mt-1 text-sm text-zinc-500 dark:text-zinc-400">Organize receitas e despesas para melhorar seus relatórios.</p></div></div>
        <button type="button" x-on:click="modal = 'category'" class="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-indigo-600 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500"><x-ui.icon name="plus" class="h-4 w-4" />Nova categoria</button>
    </div>

    <section class="rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
        <div class="grid gap-4 border-b border-zinc-200 p-5 sm:grid-cols-3 dark:border-zinc-800">
            <div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200"><x-ui.icon name="tags" class="h-5 w-5" /></span><div><p class="text-sm text-zinc-500 dark:text-zinc-400">Categorias</p><p class="mt-1 text-2xl font-semibold text-zinc-950 dark:text-white">{{ $categories->count() }}</p></div></div>
            <div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-300"><x-ui.icon name="arrow-up" class="h-5 w-5" /></span><div><p class="text-sm text-zinc-500 dark:text-zinc-400">Receitas</p><p class="mt-1 text-2xl font-semibold text-emerald-600 dark:text-emerald-400">{{ $categories->where('type', 'income')->count() }}</p></div></div>
            <div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-300"><x-ui.icon name="arrow-down" class="h-5 w-5" /></span><div><p class="text-sm text-zinc-500 dark:text-zinc-400">Despesas</p><p class="mt-1 text-2xl font-semibold text-rose-600 dark:text-rose-400">{{ $categories->where('type', 'expense')->count() }}</p></div></div>
        </div>

        <div class="overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><thead class="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500 dark:bg-zinc-950/50 dark:text-zinc-400"><tr><th class="px-5 py-3 font-semibold">Nome</th><th class="px-5 py-3 font-semibold">Tipo</th><th class="px-5 py-3 text-right font-semibold">Ações</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">
            @forelse ($categories as $category)
                <tr class="transition hover:bg-zinc-50 dark:hover:bg-zinc-950/40"><td class="px-5 py-4 font-medium text-zinc-950 dark:text-white">{{ $category->name }}</td><td class="px-5 py-4"><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold {{ $category->type === 'income' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-rose-50 text-rose-700 dark:bg-rose-950 dark:text-rose-300' }}"><x-ui.icon :name="$category->type === 'income' ? 'arrow-up' : 'arrow-down'" class="h-3.5 w-3.5" />{{ $category->type === 'income' ? 'Receita' : 'Despesa' }}</span></td><td class="px-5 py-4 text-right"><div class="inline-flex gap-2"><a href="{{ route('categories.edit', $category) }}" class="inline-flex items-center gap-1.5 rounded-lg bg-zinc-100 px-3 py-1.5 text-xs font-semibold text-zinc-700 transition hover:bg-zinc-200 dark:bg-zinc-800 dark:text-zinc-200 dark:hover:bg-zinc-700"><x-ui.icon name="edit" class="h-3.5 w-3.5" />Editar</a><button type="button" wire:click="delete({{ $category->id }})" wire:confirm="Tem certeza que deseja excluir?" class="inline-flex items-center gap-1.5 rounded-lg bg-rose-600 px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-rose-500"><x-ui.icon name="trash" class="h-3.5 w-3.5" />Excluir</button></div></td></tr>
            @empty
                <tr><td colspan="3" class="px-5 py-10 text-center text-zinc-500 dark:text-zinc-400">Nenhuma categoria cadastrada.</td></tr>
            @endforelse
        </tbody></table></div>
    </section>

    <div x-cloak x-show="modal" x-transition.opacity class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" x-on:keydown.escape.window="modal = null"><div class="absolute inset-0" x-on:click="modal = null"></div><div x-show="modal" x-transition.scale.origin.center class="relative z-10 flex max-h-[90vh] w-full max-w-xl flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-2xl dark:border-zinc-800 dark:bg-zinc-900"><div class="flex items-start justify-between gap-4 border-b border-zinc-200 px-6 py-4 dark:border-zinc-800"><div class="flex items-start gap-3"><span class="mt-0.5 flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><x-ui.icon name="tags" class="h-5 w-5" /></span><div><h2 class="text-lg font-semibold text-zinc-950 dark:text-white">Nova categoria</h2><p class="mt-1 text-sm text-zinc-500 dark:text-zinc-400">Classifique melhor seus lançamentos.</p></div></div><button type="button" x-on:click="modal = null" class="rounded-lg p-2 text-zinc-500 transition hover:bg-zinc-100 hover:text-zinc-900 dark:hover:bg-zinc-800 dark:hover:text-white" aria-label="Fechar"><x-ui.icon name="x" class="h-5 w-5" /></button></div><div class="flex-1 overflow-y-auto px-6 py-5"><livewire:categories.category-form :modal="true" :key="'categories-create-modal'" /></div></div></div>
</div>